# Sample workflow for building and deploying an Angular app to GitHub Pages
name: Build and Deploy Angular App

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Jobs for building and deploying the Angular app
jobs:
  # Job for building the Angular app
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.13.1" # Ensure the correct Node.js version
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install dependencies and build
        run: |
          cd maximilian_course/easy_task
          npm install
          npm run build --prod
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-app # Specify the name of the artifact
          path: maximilian_course/easy_task/dist/easy_task # Specify the path to the built app

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
