name: Build and Deploy Angular App

on:
  push:
    branches:
      - master

jobs:
  # Job for building the Angular app
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.13" # تأكد من تحديد إصدار Node.js المناسب لمشروعك

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies and build
        run: |
          cd maximilian_course/easy_task
          npm install
          npm run build --prod

  # Job for deploying the built app to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    needs: build # تأكد من تشغيل هذه الوظيفة بعد الانتهاء من بناء المشروع

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./maximilian_course/easy_task/docs/easy_task # تأكد من تعيين المسار الصحيح لمجلد البناء
