name: Deploy Easy Task

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: ls -R

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.13.1"

      - name: Install dependencies and build
        run: |
          cd maximilian_course/easy_task
          npm install
          npm run build --prod

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./maximilian_course/easy_task/dist/easy_task
