# Sample workflow for building and deploying an Angular app to GitHub Pages
name: Build and Deploy Angular App

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job for building the Angular app
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.13.1" # Ensure to specify the correct Node.js version for your project
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install dependencies and build
        run: |
          cd maximilian_course/easy_task
          npm install
          npm run build --prod
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-app
          path: maximilian_course/easy_task/dist/easy_task # Ensure to set the correct path to the build directory

  # Job for deploying the built app to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Ensure to run this job after the build job is completed
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: built-app
          path: maximilian_course/easy_task/dist/easy_task # Ensure to set the correct path to the build directory
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/easy_task
